blog/urls.py
from django.urls import path
from .views import (PostListView, PostDetailView, PostCreateView, PostUpdateView, PostDeleteView, UserPostListView)
from . import views

urlpatterns = [
    path('', PostListView.as_view(), name='blog-home'),
    path('user/<str:username>', UserPostListView.as_view(), name='user-posts'),
    path('post/<int:pk>/', PostDetailView.as_view(), name='post-detail'),
    path('post/new/', PostCreateView.as_view(), name='post-create'),
    #path('post/new/', views.create_post, name='post-create'),
    path('post/<int:pk>/update/', PostUpdateView.as_view(), name='post-update'),
    path('post/<int:pk>/delete/', PostDeleteView.as_view(), name='post-delete'),
    path('post/<int:pk>/comment/', views.add_comment_to_post, name='add_comment_to_post'),
    #path('post/<int:pk>/', views.add_comment, name='add_comment'),
    path('about/', views.about, name='blog-about'),
   path('comment/<int:pk>/block/', views.comment_block, name='comment_block'),
	path('comment/<int:pk>/remove/', views.comment_remove, name='comment_remove'),
]



blog_projects/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('blog.urls')),
    path('', include('users.urls')),
]

if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)
    urlpatterns += static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)

blog/models.py
from django.db import models
from django.utils import timezone
from django.contrib.auth.models import User
from django.urls import reverse
from PIL import Image
from django.db.models.signals import post_save
from django.dispatch import receiver


class Post(models.Model): 
	title = models.CharField(max_length=100, unique=True)
	slug = models.SlugField(max_length=200, unique=True)
	post_image = models.ImageField(default='post.jpg', upload_to='blog_pics')
	content = models.TextField()
	date_posted = models.DateTimeField(default=timezone.now)
	author = models.ForeignKey(User, on_delete=models.CASCADE)
	featured = models.BooleanField(default=False)

	def __str__(self):
		return self.title

	def get_absolute_url(self):
		return reverse('post-detail', kwargs={'pk': self.pk})

	def save(self, *args, **kwargs):
		super().save(*args, **kwargs)
                                  
		img = Image.open(self.post_image.path)

		if img.width > 640 or img.height > 360:
			output_size = (640, 360)
			img.thumbnail(output_size)
			img.save(self.post_image.path)  


#@receiver(post_save, sender=User)
#def create_user_post(sender, instance, created, **kwargs):
#	if created:
#		Post.objects.create(user=instance)

#@receiver(post_save, sender=User)
#def save_user_post(sender, instance, **kwargs):
#	instance.post.save()
		
class Comment(models.Model):
    post = models.ForeignKey('blog.Post', on_delete=models.CASCADE, related_name='comments')
    name = models.ForeignKey(User, on_delete=models.CASCADE)
    body = models.TextField()
    created_date = models.DateTimeField(default=timezone.now)
    active = models.BooleanField(default=True)


    class Meta:
        ordering = ['-created_date']


    def __str__(self):
        return 'Comment {} by {}' .format(self.body, self.name)




blog/forms.py
from django import forms
from .models import Comment
from django.shortcuts import render, redirect, get_object_or_404

class CommentForm(forms.ModelForm):
    class Meta:
        model = Comment
        fields = ['body',]

blog/views.py
from django.shortcuts import render, get_object_or_404, redirect
from django.contrib.auth.mixins import LoginRequiredMixin, UserPassesTestMixin
from django.contrib.auth.models import User
from django.views.generic import (ListView, DetailView, CreateView, UpdateView, DeleteView)
from .models import Post, Comment
from users.models import Profile
from .forms import CommentForm, AuthorComment
from django.contrib.auth.decorators import login_required




def home(request):
	context = {
		'posts': Post.objects.all()
	}
	return render(request, 'blog/home.html', context) 


class PostListView(ListView):
	model = Post
	template_name = 'blog/home.html' # <app>/<model>_<viewtype>.html
	context_object_name = 'posts'
	ordering = ['-date_posted'] 
	paginate_by = 2

class UserPostListView(ListView):
	model = Post
	template_name = 'blog/user_posts.html' # <app>/<model>_<viewtype>.html
	context_object_name = 'posts' 
	paginate_by = 2

	def get_queryset(self):
		user = get_object_or_404(User, username=self.kwargs.get('username'))
		return Post.objects.filter(author=user).order_by('-date_posted')

class PostDetailView(DetailView):
	model = Post

class PostCreateView(LoginRequiredMixin, CreateView):
    model = Post
    fields = ['title', 'slug', 'post_image', 'content']

    def form_valid(self, form):
        form.instance.author = self.request.user
        return super().form_valid(form)

class PostUpdateView(LoginRequiredMixin, UserPassesTestMixin, UpdateView):
	model = Post
	fields = ['title', 'post_image', 'content']

	def form_valid(self, form):
		form.instance.author = self.request.user
		return super().form_valid(form)

	def test_func(self):
		post = self.get_object()
		if self.request.user == post.author:
			return True
		return False

class PostDeleteView(LoginRequiredMixin, UserPassesTestMixin, DeleteView):
	model = Post
	success_url = '/'

	def test_func(self):
		post = self.get_object()
		if self.request.user == post.author:
			return True
		return False
	

def about(request):
	return render(request, 'blog/about.html', {'title': 'About'}) 
	
@login_required
def create_post(request):
	user = request.user
	if request.method == 'POST':
		form = PostForm(request.POST, request.FILES)
		if form.is_valid():
			post = form.save(commit=False)
			post.author = user
			post.save()
			return redirect('blog-home')
			#return redirect('post-detail', pk=post.pk)
			#return render(request, 'blog/post_detail.html', {'form': form})
	else:
		form = PostForm()
		return render(request, 'blog/post_form.html', {'form': form})





@login_required
def add_comment_to_post(request, pk):
	user = request.user
	#user = get_object_or_404(User, username=self.kwargs.get('username'))
	post = get_object_or_404(Post, pk=pk)
	#profile = get_object_or_404(Profile, user=user)
	#user = get_object_or_404(User, username=self.kwargs.get('username'))
	#email = user.email
	#image = profile.image.url
	if request.method == 'POST':
		form = CommentForm(request.POST)
		if form.is_valid():
			comment = form.save(commit=False)
			comment.post = post
			comment.name = user
			#comment.image = image
			#comment.email = email
			comment.save()
			return redirect('post-detail', pk=post.pk)
	else:
		form = CommentForm()
	return render(request, 'blog/add_comment_to_post.html', {'form': form})
# Create your views here.
@login_required
def comment_block(request, pk):
    comment = get_object_or_404(Comment, pk=pk)
    if comment.active is True:
    	comment.active = False
    	comment.save()
    	return redirect('post-detail', pk=comment.post.pk)
    else:
    	comment.active = True
    	comment.save()
    	return redirect('post-detail', pk=comment.post.pk)

@login_required
def comment_remove(request, pk):
    comment = get_object_or_404(Comment, pk=pk)
    comment.delete()
    return redirect('post-detail', pk=comment.post.pk)



templates/blog/add_comment_to_post.html
{% extends 'base.html' %}
{% load static %}
{% block content %}

<div class="container" style="max-width: 500px; align-self: center;">
<div class="card my-4">
    <h5 class="card-header">Leave a Comment:</h5>
    <div class="card-body">
        <form method="POST" class="post-form">{% csrf_token %}
            <!--<div class="form-group">
                <p>
                    <label for="id_name">Name:</label>
                    <input type="text" id="id_name" class="form-control" value="{{ user.username }}" maxlength="30" name="name" readonly>
                </p>
            </div>-->

            <div class="form-group">
                <label for="id_body">Body:</label>
                <textarea id="id_body" value="" name="body" class="form-control" rows="3"></textarea>
            </div>

            <button type="submit" class="save btn btn-primary">Submit</button>

        </form>
    </div>
</div>
</div>

{% endblock %}

templates/blog/home.html
{% extends 'base.html' %}
{% load static %}
{% block content %}


  <!-- Page Content -->
  <div class="container">

    <div class="row">

      <!-- Blog Entries Column -->
      <div class="col-md-8">

        <h1 class="my-4">Posts
        </h1>

        <!-- Blog Post -->
        {% for post in posts %}
        <div class="card mb-4">
        <div class="container" style="max-width: 720px; margin: 10px 0 0 5px;">
            {% if post.post_image.url == '/media/post.jpg' %}
            <img class="card-img-top" src="{% static 'img/post.jpg' %}" alt="" width="640" height="360">
            {% else %}
            <img class="card-img-top" src="{{ post.post_image.url }}" alt="" width="640" height="360">
            {% endif %}
            </div>
            <div class="card-body"><h2 class="card-title"><a class="card-title" href="{% url 'post-detail' post.id %}">
                {{ post.title }}
            </a></h2><p class="card-text">{{ post.content|truncatewords:28 }}   <a class="btn btn-primary"
             href="{% url 'post-detail' post.id %}"> Read More &rarr;</a></p></div>

             <div class="card-footer text-muted">
                 {% if post.author.profile.image.url == '/media/default.jpg' %}
                 <img class="rounded-circle article-img" src="{% static 'img/default.jpg' %}" alt="" width="50" height="50">
                 {% else %}
                 <img class="rounded-circle article-img" src="{{ post.author.profile.image.url }}" alt="" width="50" height="50">
                 {% endif %}
                 <a class="mr-2" href="{% url 'user-posts' post.author.username %}">By {{ post.author }}</a>
                 <small class="text-muted">on {{ post.date_posted|date:"F d, Y" }}</small>
             </div>

             <div class="container">
                 <p><a href="{% url 'post-detail' pk=post.pk %}">
                     {% if post.comments.count == 0 %}
                     Comment: {{ post.comments.count }}
                     {% else %}
                     Comments: {{ post.comments.count }}
                     {% endif %}
                 </a></p>
             </div>
             </div>
             {% endfor %}
        <!-- Pagination -->

        {% if is_paginated %}
        
        {% if page_obj.has_previous %}
        <a class="btn btn-outline-info mb-4" href="?page=1">First</a>
        <a class="btn btn-outline-info mb-4" href="?page={{ page_obj.previous_page_number }}">&larr; Newer</a>
        {% endif %}

        {% for num in page_obj.paginator.page_range %}
        {% if page_obj.number == num %}
        <a class="btn btn-info mb-4" href="?page={{ num }}">{{ num }}</a>
        {% elif num > page_obj.number|add:'-3' and num < page_obj.number|add:'3' %}
        <a class="btn btn-outline-info mb-4" href="?page={{ num }}">{{ num }}</a>
        {% endif %}
        {% endfor %}

        {% if page_obj.has_next %}
        <a class="btn btn-outline-info mb-4" href="?page={{ page_obj.next_page_number}}">Older &rarr;</a>
        <a class="btn btn-outline-info mb-4" href="?page={{ page_obj.paginator.num_pages }}">Last</a>
        {% endif %}
        
        {% endif %}

      </div>

      <!-- Sidebar Widgets Column -->
      <div class="col-md-4">

          {% include 'sidebar.html' %}
        
      </div>

    </div>
    <!-- /.row -->

  </div>
  <!-- /.container -->
<!-- Footer -->
<footer class="py-5 bg-dark">
  <div class="container">
    <p class="m-0 text-center text-white">Copyright &copy; Blog Projects 2020</p>
  </div>
  <!-- /.container -->
</footer>

{% endblock %}

templates/blog/post_confirm_delete.html
{% extends 'base.html' %}
{% load static %}
{% block content %}

<div class="container" style="max-width: 700px; align-self: center;">
<div class="card my-4">
    <h5 class="card-header">Delete Post</h5>
    <div class="card-body">
        <form method="POST" action="" enctype="multipart/form-data">{% csrf_token %}
            <fieldset class="form-group">
                <p>Are you sure you want to delete the post "{{ object.title }}" ?</p>
            </fieldset>
            <div class="form-group">
                <button class="btn btn-outline-danger" type="submit">Yes, Delete</button>
                <a class="btn btn-outline-secondary" href="{% url 'post-detail' object.id %}">Cancel</a>
            </div>
        </form>
    </div>
</div>
</div>

{% endblock %}

templates/blog/post_detail.html
{% extends 'base.html' %}
{% load static %}
{% block content %}

  <!-- Page Content -->
  <div class="container">

    <div class="row">

      <!-- Post Content Column -->
      <div class="col-lg-8">

        <!-- Title -->
        <h1 class="mt-4">{{ object.title }}</h1>

        <!-- Author -->
        <p class="lead">
            {% if post.author.profile.image.url == '/media/default.jpg' %}
            <img class="rounded-circle article-img" src="{% static 'img/default.jpg' %}" alt="" width="50" height="50">
            {% else %}
            <img class="rounded-circle article-img" src="{{ post.author.profile.image.url }}" alt="" width="50" height="50">
            {% endif %}
          by
          <a href="{% url 'user-posts' post.author.username %}">{{ post.author }}</a>
        </p>

        <hr>

        <!-- Date/Time -->
        <p>Posted on {{ post.date_posted|date:"F d, Y" }}
            {% if request.user == post.author %}
            <a class="btn btn-secondary btn-sm mt-1 mb-1" href="{% url 'post-update' object.id %}">Edit</a>
            <a class="btn btn-danger btn-sm mt-1 mb-1" href="{% url 'post-delete' object.id %}">Delete</a>
            {% endif %}
        </p>

        <hr>

        <!-- Preview Image -->
        {% if post.post_image.url == '/media/post.jpg' %}
        <img class="card-img-top" src="{% static 'img/post.jpg' %}" alt="Card image cap" width="640" height="360">
        {% else %}
        <img class="card-img-top" src="{{ post.post_image.url }}" alt="Card image cap" width="640" height="360">
        {% endif %}

        <hr>

        <!-- Post Content -->
        <p class="lead">{{ object.content }}</p>

        <hr>

        <!-- Comments Form -->
        <p><a class="btn btn-primary" href="{% url 'add_comment_to_post' pk=post.pk %}">Add Comment</a></p>

        <!-- Single Comment -->
        {% for comment in post.comments.all %}
        {% if comment.active == True %}
        <div class="media mb-4">
          {% if comment.name.profile.image.url == '/media/default.jpg' %}
          <img class="d-flex mr-3 rounded-circle" src="{% static 'img/default.jpg' %}" alt="" width="50" height="50">
          {% else %}
          <img class="d-flex mr-3 rounded-circle" src="{{ comment.name.profile.image.url }}" alt="" width="50" height="50">
          {% endif %}
          <div class="media-body">
            <h5 class="mt-0">{{ comment.name }}  <small class="ml-2" styles="font-family:all;"> to {% if comment.name == post.author %}self {% else %}{{ post.author.username }}{% endif %}</small></h5>
            <i>{{ comment.created_date|date:"F d, Y" }}</i>
            {% if user.is_superuser == True %}
            <a href="{% url 'comment_remove' pk=comment.pk %}"><span>delete</span></a>
            <a href="{% url 'comment_block' pk=comment.pk %}"><span>block</span></a>
            {% endif %}
            <p>{{ comment.body|linebreaks }}</p>
          </div>
        </div>
        {% endif %}
        {% empty %}
        <p>No comments here yet:</p>
        {% endfor %}
      </div>
            
      <!-- Sidebar Widgets Column -->
      <div class="col-md-4">

        {% include 'sidebar.html' %}
        
      </div>

    </div>
    <!-- /.row -->

  </div>
  <!-- /.container -->

  {% endblock %}

templates/blog/post_form.html
{% extends 'base.html' %}
{% load crispy_forms_tags %}
{% load static %}

{% block content %}

<div class="container" style="max-width:700px; align-self: center;">
<div class="card my-4">
    <h5 class="card-header">Blog Post:</h5>
    {% if post is new %}
    <div class="card-body">
        <form method="POST" action="" enctype="multipart/form-data">{% csrf_token %}
            <fieldset class="form-group">
                {{ form|crispy }}
            </fieldset>
        <div class="form-group"> 
            <button class="btn btn-outline-info" type="submit">Post</button>
        </div>
        </form>
    </div>
    {% else %}
    <div class="card-body">
        <form method="POST" action="" enctype="multipart/form-data">{% csrf_token %}
            <fieldset class="form-group">
                {{ form|crispy }}
            </fieldset>
        <div class="form-group"> 
            <button class="btn btn-outline-info" type="submit">Update</button>
        </div>
        </form>
    </div>
    {% endif %}
</div>
</div>
{% endblock %}

templates/blog/user_posts.html
{% extends 'base.html' %}
{% load static %}
{% block content %}

<div class="container">
    <div class="row">
        <div class="col-lg-8">

            <h3 class="mt-4">Posts by {{ view.kwargs.username }} ({{ page_obj.paginator.count }})</h3>
            {% for post in posts %}
            <div class="card mb-4">
                <div class="card-header">
                    <p class="lead">
                        {% if post.author.profile.image.url == '/media/default.jpg' %}
                        <img class="rounded-circle article-img" src="{% static 'img/default.jpg' %}" alt="" width="50" height="50">
                        {% else %}
                        <img class="rounded-circle article-img" src="{{ post.author.profile.image.url }}" alt="" width="50" height="50">
                        {% endif %}
                        <small class="text-muted">on {{ post.date_posted|date:"F d, Y" }}</small>
                    </p>
                </div>

                <div class="container" style="max-width: 720px; margin:10px 0 0 5px;">
                {% if post.post_image.url == '/media/post.jpg' %}
                <img class="card-img-top" src="{% static 'img/post.jpg' %}" alt="" width="640" height="360">
                {% else %}
                <img class="card-img-top" src="{{ post.post_image.url }}" alt="" width="640" height="360">
                {% endif %}
                </div>

                <div class="card-body">
                    <a class="card-title" href="{% url 'post-detail' post.id %}">
                        <h2 class="card-title">{{ post.title }}</h2>
                    </a>
                    <p class="card-text">{{ post.content|truncatewords:28 }}   <a class="btn btn-primary" href="{% url 'post-detail' post.id %}">Read More &rarr;</a></p>
                </div>

                <div class="container">
                    <p><a href="{% url 'post-detail' pk=post.pk %}">
                        {% if post.comments.count == 0 %}
                        Comment: {{ post.comments.count }}
                        {% else %}
                        Comments: {{ post.comments.count }}
                        {% endif %}
                    </a></p>
                </div>
            </div>
            {% endfor %}

            {% if is_paginated %}
            {% if page_obj.has_previous %}
            <a class="btn btn-outline-info mb-4" href="?page=1">First</a>
            <a class="btn btn-outline-info mb-4" href="?page={{ page_obj.previous_page_number }}">&larr; Newer</a>
            {% endif %}

            {% for num in page_obj.paginator.page_range %}
            {% if page_obj.number == num %}
            <a class="btn btn-info mb-4" href="?page={{ num }}">{{ num }}</a>
            {% elif num > page_obj.number|add:'-3' and num < page_obj.number|add:'3' %}
            <a class="btn btn-outline-info mb-4" href="?page={{ num }}">{{ num }}</a>
            {% endif %}
            {% endfor %}

            {% if page_obj.has_next %}
            <a class="btn btn-outline-info mb-4" href="?page={{ page_obj.next_page_number }}">Older &rarr;</a>
            <a class="btn btn-outline-info mb-4" href="?page={{ page_obj.paginator.num_pages }}">Last</a>
            {% endif %}

            {% endif %}
        </div>

        <div class="col-md-4">
            {% include 'sidebar.html' %}
        </div>
    </div>
</div>
{% endblock %}